#!/bin/sh

url="${WTTRURL:-wttr.in}"
weatherreport="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"

# Get a weather report from 'wttr.in' and save it locally.
getforecast() { timeout --signal=1 2s curl -sf "$url/$LOCATION?format=%t" > "$weatherreport" || exit 1; }

readfile() { weatherdata="$(cat "$weatherreport")" ;}

case $BLOCK_BUTTON in
	1) curl wttr.in > /home/kat/.cache/fullweather; setsid -f "$TERMINAL" -e less -Sf "/home/kat/.cache/fullweather" ;;
	2) getforecast && showweather ;;
	3) notify-send "🌈 Weather module" "\- Left click for full forecast.
- Middle click to update forecast.
☔: Chance of rain/snow
🥶: Daily low
🌞: Daily high" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
getforecast
printf " %s | \n" "$(cat ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport | grep -o '[0-9]\+°')"
