#!/bin/sh

case $BLOCK_BUTTON in
    1) setsid -w -f "${TERMINAL:-xterm}" -e pulsemixer; pkill -RTMIN+10 "${STATUSBAR:-dwmblocks}" ;;
    2) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    4) pactl set-sink-volume @DEFAULT_SINK@ +1% ;;
    5) pactl set-sink-volume @DEFAULT_SINK@ -1% ;;
    3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
    6) setsid -f "${TERMINAL:-xterm}" -e "${EDITOR:-vi}" "$0" ;;
esac

muted="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"
[ "$muted" = "yes" ] && printf "󰖁  |"  && exit

vol="$(pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]\+%' | head -1 | tr -d '%')"

if [ "$vol" -ge 70 ]; then
    icon="󰕾"
elif [ "$vol" -ge 30 ]; then
    icon="󰖀"
elif [ "$vol" -ge 1 ]; then
    icon="󰕿"
else
    printf "󰖁 |" && exit
fi

echo "$icon $vol% |"
